"$schema" = 'https://starship.rs/config-schema.json'

format = """$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$fill\
$nodejs\
$bun\
$deno\
$golang\
$python\
$cmd_duration $jobs $datetime $time $line_break\
$character"""

add_newline = false

[character]
disabled = false
success_symbol = '[❯](bold green) '
error_symbol = '[✖](bold red) '


[directory]
style = "blue"
read_only = " "
truncate_to_repo = false
truncation_length = 6
truncation_symbol = '…/'

[line_break]
disabled = false

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bright-black"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_metrics]
disabled = false

[fill]
symbol = " "

[nodejs]
symbol = " "
format = "[$symbol($version )]($style)"

[golang]
symbol = " "
format = "[$symbol($version )]($style)"

[python]
symbol = " "
format = "[$symbol($version )]($style)"

[php]
symbol = " "
format = "[$symbol($version )]($style)"

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[time]
disabled = false
style = "bold white"
format = "[$time]($style)"
time_format = "%F %T"
